apiVersion: v1
kind: Secret
metadata:
  name: db
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "111"
    "helm.sh/resource-policy": keep
type: Opaque
data:
  DB_HOST: {{ include "revo.db.address" . | b64enc }}
  DB_PORT: {{ include "revo.db.port" . | b64enc }}
  DB_NAME: {{ include "revo.db.name" . | b64enc }}
  DB_USER: {{ include "revo.db.username" . | b64enc }}
  DB_PASS: {{ include "revo.db.password" . | b64enc }}
  