name: CI
run-name: "#${{ github.run_number }} ${{ github.event.head_commit.message }}"

on:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: oskarriczia/revo

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          provenance: false
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Test
        run: make tests